# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9

exclude: "^$"

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb", "3_000"]
      - id: check-merge-conflict
      - id: check-docstring-first
  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # Python linting/syntax checking
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: ^tests/
        args: [--max-line-length=88]

  # Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v2.20.3"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Python check docstrings
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        exclude: ^tests/
        args:
        - --ignore=D103, D213
